[changelog]
header = "# Changelog\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% if commit.scope %} ({{ commit.scope }}){% endif %}
{% endfor %}
{% endfor %}
"""
trim = true
postprocess = ""
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

[git.conventional_commits]
types = [
  { type = "feat",      group = "Features",       section = "Features" },
  { type = "fix",       group = "Bug Fixes",      section = "Bug Fixes" },
  { type = "docs",      group = "Documentation",  section = "Documentation" },
  { type = "refactor",  group = "Refactoring",    section = "Code Refactoring" },
  { type = "perf",      group = "Performance",    section = "Performance" },
  { type = "test",      group = "Tests",          section = "Tests" },
  { type = "ci",        group = "CI/CD",          section = "CI/CD" },
  { type = "chore",     group = "Chores",         section = "Chores" },
  { type = "style",     group = "Style",          section = "Style" },
]
